sudo: required

env:
  - DOCKER_IMAGE=daixijun1990/aliyun-cli
  - DOCKER_TAG=3.0.8

services:
  - docker

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build --build-arg VERSION=${DOCKER_TAG} --tag $DOCKER_IMAGE:$DOCKER_TAG --tag $DOCKER_IMAGE:latest .

after_success:
  - docker push $DOCKER_IMAGE:$DOCKER_TAG
  - docker push $DOCKER_IMAGE:latest
