sudo: required

env:
  DOCKER_IMAGE=daixijun1990/aliyun-cli
  DOCKER_TAG=3.0.7

services:
  - docker

script:
  - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
  - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:$DOCKER_TAG
  - docker push $DOCKER_IMAGE:latest